[package]
name = "toniator-patterns"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
toniator-domain = { path = "../toniator-domain" }
toniator-geometry = { path = "../toniator-geometry" }
toniator-sampling = { path = "../toniator-sampling" }

[lib]
path = "src/lib.rs"
