use crate::model::{Document, RenderVariant, Treatment, WebShape};
use crate::persistence::atomic_write;
use crate::render::{Channel, Mark, MarkGeometry, generate_document_marks, source_dimensions};
use anyhow::Result;
use std::fmt::Write as _;
use std::path::Path;

pub fn export_svg(path: &Path, document: &Document) -> Result<()> {
    document.validate()?;
    if let RenderVariant::WebCurveV1 { settings } = &document.render {
        return export_curve_svg(path, document, settings);
    }
    let (artboard_width, artboard_height) = match &document.render {
        RenderVariant::NativeBasicV1 => source_dimensions(&document.source)?,
        RenderVariant::WebShapeV1 { settings } => (settings.output_width, settings.output_height),
        RenderVariant::WebCurveV1 { settings } => (settings.output_width, settings.output_height),
    };
    let mark_set = generate_document_marks(document)?;
    let scale_x = artboard_width as f32 / mark_set.width as f32;
    let scale_y = artboard_height as f32 / mark_set.height as f32;
    let mut svg = String::with_capacity(mark_set.marks.len() * 110);
    writeln!(
        svg,
        r#"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="{}" height="{}" viewBox="0 0 {} {}" style="isolation:isolate">"#,
        artboard_width, artboard_height, artboard_width, artboard_height
    )?;
    writeln!(
        svg,
        "  <title>Toniator — {}</title>",
        xml_escape(&document.source.name)
    )?;
    writeln!(
        svg,
        "  <desc>Editable CMYK halftone generated by Toniator</desc>"
    )?;
    writeln!(
        svg,
        "  <rect id=\"toniator-paper\" x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"#ffffff\"/>"
    )?;

    for layer in mark_set.layers.iter().filter(|layer| layer.enabled) {
        let channel = layer.channel;
        let (r, g, b) = layer.color;
        let label = match layer.channel {
            Channel::Cyan => "Cyan",
            Channel::Magenta => "Magenta",
            Channel::Yellow => "Yellow",
            Channel::Black => "Black",
        };
        writeln!(
            svg,
            "  <g id=\"toniator-{}\" inkscape:groupmode=\"layer\" inkscape:label=\"{}\" fill=\"#{:02x}{:02x}{:02x}\" opacity=\"{}\" style=\"mix-blend-mode:multiply\">",
            channel.id(),
            label,
            r,
            g,
            b,
            number(layer.opacity)
        )?;
        for (index, mark) in mark_set
            .marks
            .iter()
            .filter(|mark| mark.channel == channel)
            .enumerate()
        {
            write_mark(&mut svg, scale_mark(*mark, scale_x, scale_y), index)?;
        }
        writeln!(svg, "  </g>")?;
    }
    writeln!(svg, "</svg>")?;
    atomic_write(path, svg.as_bytes())
}

fn export_curve_svg(
    path: &Path,
    document: &Document,
    settings: &crate::model::WebCurveSettings,
) -> Result<()> {
    let source = crate::render::decode_source(&document.source, 2400)?;
    let geometry = crate::curve_render::generate_curve_geometry(&source, settings)?;
    let mut svg = String::new();
    writeln!(
        svg,
        r#"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="{}" height="{}" viewBox="0 0 {} {}" style="isolation:isolate">"#,
        geometry.width, geometry.height, geometry.width, geometry.height
    )?;
    writeln!(
        svg,
        "  <title>Toniator — {}</title>",
        xml_escape(&document.source.name)
    )?;
    writeln!(
        svg,
        "  <desc>Editable CMYK full-width curve halftone generated by Toniator</desc>"
    )?;
    writeln!(
        svg,
        "  <defs><clipPath id=\"toniator-artboard-clip\"><rect x=\"0\" y=\"0\" width=\"{}\" height=\"{}\"/></clipPath></defs>",
        geometry.width, geometry.height
    )?;
    writeln!(
        svg,
        "  <rect id=\"toniator-paper\" x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"#ffffff\"/>"
    )?;
    for layer in &geometry.layers {
        let channel = layer.layer.channel;
        let (r, g, b) = layer.layer.color;
        let label = match channel {
            Channel::Cyan => "Cyan",
            Channel::Magenta => "Magenta",
            Channel::Yellow => "Yellow",
            Channel::Black => "Black",
        };
        writeln!(
            svg,
            "  <g id=\"toniator-{}\" inkscape:groupmode=\"layer\" inkscape:label=\"{}\" fill=\"#{:02x}{:02x}{:02x}\" opacity=\"{}\" style=\"mix-blend-mode:multiply\" clip-path=\"url(#toniator-artboard-clip)\">",
            channel.id(),
            label,
            r,
            g,
            b,
            number(layer.layer.opacity)
        )?;
        for (index, outline) in layer.outlines.iter().enumerate() {
            writeln!(
                svg,
                "    <path id=\"{}-curve-{}\" d=\"{}\" fill-rule=\"nonzero\"/>",
                channel.id(),
                index,
                outline.to_svg_path_data()
            )?;
        }
        writeln!(svg, "  </g>")?;
    }
    writeln!(svg, "</svg>")?;
    atomic_write(path, svg.as_bytes())
}

fn scale_mark(mut mark: Mark, scale_x: f32, scale_y: f32) -> Mark {
    mark.x *= scale_x;
    mark.y *= scale_y;
    mark.extent *= (scale_x + scale_y) / 2.0;
    mark.thickness *= (scale_x + scale_y) / 2.0;
    mark
}

fn write_mark(svg: &mut String, mark: Mark, index: usize) -> std::fmt::Result {
    let prefix = mark.channel.id();
    if let MarkGeometry::WebShape(shape) = mark.geometry {
        return writeln!(
            svg,
            "    <path id=\"{}-mark-{}\" d=\"{}\"/>",
            prefix,
            index,
            web_shape_path_data(mark, shape)
        );
    }
    match mark.treatment {
        Treatment::Dots => writeln!(
            svg,
            "    <circle id=\"{}-mark-{}\" cx=\"{}\" cy=\"{}\" r=\"{}\"/>",
            prefix,
            index,
            number(mark.x),
            number(mark.y),
            number(mark.extent)
        ),
        Treatment::Squares => writeln!(
            svg,
            "    <rect id=\"{}-mark-{}\" x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" transform=\"rotate({} {} {})\"/>",
            prefix,
            index,
            number(mark.x - mark.extent / 2.0),
            number(mark.y - mark.extent / 2.0),
            number(mark.extent),
            number(mark.extent),
            number(mark.angle),
            number(mark.x),
            number(mark.y)
        ),
        Treatment::Lines => writeln!(
            svg,
            "    <rect id=\"{}-mark-{}\" x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" transform=\"rotate({} {} {})\"/>",
            prefix,
            index,
            number(mark.x - mark.extent / 2.0),
            number(mark.y - mark.thickness / 2.0),
            number(mark.extent),
            number(mark.thickness),
            number(mark.angle),
            number(mark.x),
            number(mark.y)
        ),
    }
}

fn web_shape_path_data(mark: Mark, shape: WebShape) -> String {
    let transform = |x: f32, y: f32| {
        let radians = mark.angle.to_radians();
        let (sin, cos) = radians.sin_cos();
        let x = x * mark.extent;
        let y = y * mark.extent;
        (mark.x + x * cos - y * sin, mark.y + x * sin + y * cos)
    };
    let point = |(x, y)| {
        let (x, y) = transform(x, y);
        format!("{} {}", number(x), number(y))
    };
    if shape == WebShape::Circle {
        let p = [
            (0.0, -0.5),
            (0.276, -0.5),
            (0.5, -0.276),
            (0.5, 0.0),
            (0.5, 0.276),
            (0.276, 0.5),
            (0.0, 0.5),
            (-0.276, 0.5),
            (-0.5, 0.276),
            (-0.5, 0.0),
            (-0.5, -0.276),
            (-0.276, -0.5),
            (0.0, -0.5),
        ];
        return format!(
            "M {} C {} {} {} C {} {} {} C {} {} {} C {} {} {} Z",
            point(p[0]),
            point(p[1]),
            point(p[2]),
            point(p[3]),
            point(p[4]),
            point(p[5]),
            point(p[6]),
            point(p[7]),
            point(p[8]),
            point(p[9]),
            point(p[10]),
            point(p[11]),
            point(p[12]),
        );
    }
    let points: &[(f32, f32)] = match shape {
        WebShape::Circle => unreachable!(),
        WebShape::Rectangle => &[(-0.45, -0.45), (0.45, -0.45), (0.45, 0.45), (-0.45, 0.45)],
        WebShape::Triangle => &[(0.0, -0.52), (0.5, 0.4), (-0.5, 0.4)],
        WebShape::Pentagon => &[
            (0.0, -0.5),
            (0.4755, -0.1545),
            (0.2939, 0.4045),
            (-0.2939, 0.4045),
            (-0.4755, -0.1545),
        ],
        WebShape::Hexagon => &[
            (0.433, -0.25),
            (0.433, 0.25),
            (0.0, 0.5),
            (-0.433, 0.25),
            (-0.433, -0.25),
            (0.0, -0.5),
        ],
    };
    let mut data = format!("M {}", point(points[0]));
    for &vertex in &points[1..] {
        data.push_str(" L ");
        data.push_str(&point(vertex));
    }
    data.push_str(" Z");
    data
}

fn number(value: f32) -> String {
    let mut number = format!("{value:.3}");
    while number.contains('.') && number.ends_with('0') {
        number.pop();
    }
    if number.ends_with('.') {
        number.pop();
    }
    if number == "-0" { "0".into() } else { number }
}

fn xml_escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::SourceArtwork;
    use image::{DynamicImage, ImageFormat, Rgb, RgbImage};
    use std::io::Cursor;

    fn source_png() -> Vec<u8> {
        let image = RgbImage::from_fn(48, 32, |x, y| {
            Rgb([(x * 5) as u8, (y * 7) as u8, ((x + y) * 3) as u8])
        });
        let mut bytes = Cursor::new(Vec::new());
        DynamicImage::ImageRgb8(image)
            .write_to(&mut bytes, ImageFormat::Png)
            .unwrap();
        bytes.into_inner()
    }

    #[test]
    fn svg_has_editable_named_layers_and_no_source_image() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("result.svg");
        let document = Document::new(SourceArtwork {
            name: "gradient.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        for channel in ["cyan", "magenta", "yellow", "black"] {
            assert!(svg.contains(&format!("id=\"toniator-{channel}\"")));
        }
        assert!(svg.contains("<circle"));
        assert!(svg.contains("mix-blend-mode:multiply"));
        assert!(!svg.contains("<image"));
        let options = usvg::Options::default();
        usvg::Tree::from_data(svg.as_bytes(), &options).unwrap();
    }

    #[test]
    fn export_preserves_artboards_larger_than_preview_cap() {
        let image = RgbImage::from_pixel(3001, 2, Rgb([120, 40, 200]));
        let mut bytes = Cursor::new(Vec::new());
        DynamicImage::ImageRgb8(image)
            .write_to(&mut bytes, ImageFormat::Png)
            .unwrap();
        let document = Document::new(SourceArtwork {
            name: "wide.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(bytes.into_inner()),
        });
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("wide.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        assert!(svg.contains("width=\"3001\" height=\"2\" viewBox=\"0 0 3001 2\""));
    }

    #[test]
    fn web_export_uses_the_preview_mark_set_and_resolved_layers() {
        use crate::model::{Ink, RenderVariant, ValueMode, WebShape, WebShapeSettings};
        use crate::render::generate_document_marks;

        let mut document = Document::new(SourceArtwork {
            name: "black.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        let mut settings = WebShapeSettings {
            output_width: 120,
            output_height: 80,
            long_edge_cells: 6.0,
            grid_scale: 76.0,
            min_mark: 4.0,
            max_mark: 90.0,
            value_mode: ValueMode::SingleChannel,
            single_channel: Ink::Black,
            shared_shape: WebShape::Triangle,
            ..Default::default()
        };
        for ink in Ink::ALL {
            settings.channels.get_mut(ink).enabled = ink == Ink::Black;
        }
        settings.channels.k.color = "#123456".into();
        settings.channels.k.opacity = 0.37;
        document.render = RenderVariant::WebShapeV1 {
            settings: Box::new(settings),
        };

        let resolved = generate_document_marks(&document).unwrap();
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("web.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        assert!(svg.contains("width=\"120\" height=\"80\" viewBox=\"0 0 120 80\""));
        assert!(svg.contains("id=\"toniator-black\""));
        assert!(svg.contains("fill=\"#123456\" opacity=\"0.37\""));
        assert!(!svg.contains("id=\"toniator-cyan\""));
        assert!(!svg.contains("id=\"toniator-magenta\""));
        assert!(!svg.contains("id=\"toniator-yellow\""));
        assert!(!svg.contains("<image"));
        assert_eq!(svg.matches("<path id=\"").count(), resolved.marks.len());
        assert!(
            svg.contains(" L "),
            "triangle geometry must remain editable paths"
        );
        usvg::Tree::from_data(svg.as_bytes(), &usvg::Options::default()).unwrap();
    }

    #[test]
    fn curve_export_uses_canonical_preview_outlines_and_editable_layers() {
        use crate::curve_render::generate_curve_geometry;
        use crate::model::{Ink, RenderVariant, ValueMode, WebCurveSettings};
        use crate::render::decode_source;

        let mut document = Document::new(SourceArtwork {
            name: "black.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        let mut settings = WebCurveSettings {
            output_width: 120,
            output_height: 80,
            long_edge_cells: 8.0,
            value_mode: ValueMode::SingleChannel,
            single_channel: Ink::Black,
            ..Default::default()
        };
        for ink in Ink::ALL {
            settings.channels.get_mut(ink).enabled = ink == Ink::Black;
        }
        settings.channels.k.color = "#123456".into();
        settings.channels.k.opacity = 0.37;
        document.render = RenderVariant::WebCurveV1 {
            settings: Box::new(settings.clone()),
        };
        let source = decode_source(&document.source, 2400).unwrap();
        let geometry = generate_curve_geometry(&source, &settings).unwrap();
        let expected = geometry
            .layers
            .iter()
            .map(|layer| layer.outlines.len())
            .sum::<usize>();
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("curve.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        assert!(svg.contains("width=\"120\" height=\"80\""));
        assert!(svg.contains("clip-path=\"url(#toniator-artboard-clip)\""));
        assert!(svg.contains("id=\"toniator-black\""));
        assert!(svg.contains("fill=\"#123456\" opacity=\"0.37\""));
        assert_eq!(svg.matches("-curve-").count(), expected);
        assert!(!svg.contains("<image"));
        usvg::Tree::from_data(svg.as_bytes(), &usvg::Options::default()).unwrap();
    }
}
