[package]
name = "toniator-render"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
rayon.workspace = true
toniator-domain = { path = "../toniator-domain" }
toniator-geometry = { path = "../toniator-geometry" }

[lib]
path = "src/lib.rs"
