use crate::CancellationToken;
use crate::artwork_pipeline::{ChannelAssignment, LegacyCompatibilityAssignment};
use crate::model::{Document, ExportBackground, RenderVariant, Treatment};
use crate::pattern::{
    CanonicalBlendMode, CanonicalLayer, CanonicalPatternOutput, GeometryPolarity,
    NetworkPatternOutput, RegionPatternOutput,
};
use crate::persistence::atomic_write_cancellable;
use crate::render::{
    Channel, Mark, MarkGeometry, MarkSet, ResolvedWebShape,
    generate_document_pattern_output_cancellable, source_dimensions,
};
use anyhow::Result;
use std::fmt::Write as _;
use std::path::Path;

pub fn export_svg(path: &Path, document: &Document) -> Result<()> {
    export_svg_cancellable(path, document, &CancellationToken::new())
}

pub fn export_svg_cancellable(
    path: &Path,
    document: &Document,
    token: &CancellationToken,
) -> Result<()> {
    token.checkpoint()?;
    let mut canonical = document.clone();
    let source_size = source_dimensions(&canonical.source)?;
    canonical.normalize_canvas_aspect(source_size.0, source_size.1);
    canonical.canonicalize_pipeline_facades()?;
    let document = &canonical;
    document.validate()?;
    let output = generate_document_pattern_output_cancellable(document, token)?;
    match &output {
        CanonicalPatternOutput::Marks(output) => {
            export_mark_svg(path, document, &output.geometry, token)
        }
        CanonicalPatternOutput::Paths(output) => {
            export_curve_svg(path, document, &output.geometry, token)
        }
        CanonicalPatternOutput::Regions(_)
        | CanonicalPatternOutput::Network(_)
        | CanonicalPatternOutput::Composite(_) => {
            let bytes =
                canonical_pattern_svg_bytes_cancellable(&output, &document.source.name, token)?;
            atomic_write_cancellable(path, &bytes, token)
        }
    }
}

fn export_mark_svg(
    path: &Path,
    document: &Document,
    mark_set: &MarkSet,
    token: &CancellationToken,
) -> Result<()> {
    let (artboard_width, artboard_height) = match &document.render {
        RenderVariant::NativeBasicV1 => source_dimensions(&document.source)?,
        RenderVariant::WebShapeV1 { settings } => (settings.output_width, settings.output_height),
        RenderVariant::WebCurveV1 { settings } => (settings.output_width, settings.output_height),
    };
    let scale_x = artboard_width as f32 / mark_set.width as f32;
    let scale_y = artboard_height as f32 / mark_set.height as f32;
    let mut svg = String::with_capacity(mark_set.marks.len() * 110);
    writeln!(
        svg,
        r#"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="{}" height="{}" viewBox="0 0 {} {}" style="isolation:isolate">"#,
        artboard_width, artboard_height, artboard_width, artboard_height
    )?;
    writeln!(
        svg,
        "  <title>Toniator — {}</title>",
        xml_escape(&document.source.name)
    )?;
    writeln!(
        svg,
        "  <desc>Editable {} halftone generated by Toniator</desc>",
        if document.artwork_pipeline.output_model == crate::artwork_pipeline::OutputModel::RgbScreen
        {
            "RGB screen"
        } else {
            "CMYK ink"
        }
    )?;
    write_export_background(&mut svg, document.appearance.export_background)?;

    for layer in mark_set.layers.iter().filter(|layer| layer.enabled) {
        token.checkpoint()?;
        let channel = layer.channel;
        let (r, g, b) = layer.color;
        let label = match layer.channel {
            Channel::Cyan => "Cyan",
            Channel::Magenta => "Magenta",
            Channel::Yellow => "Yellow",
            Channel::Black => "Black",
            Channel::Red => "Red",
            Channel::Green => "Green",
            Channel::Blue => "Blue",
        };
        writeln!(
            svg,
            "  <g id=\"toniator-{}\" inkscape:groupmode=\"layer\" inkscape:label=\"{}\" fill=\"#{:02x}{:02x}{:02x}\" opacity=\"{}\" style=\"mix-blend-mode:{}\">",
            channel.id(),
            label,
            r,
            g,
            b,
            number(layer.opacity),
            if document.artwork_pipeline.output_model
                == crate::artwork_pipeline::OutputModel::RgbScreen
            {
                "screen"
            } else {
                "multiply"
            }
        )?;
        for (index, mark) in mark_set
            .marks
            .iter()
            .filter(|mark| mark.channel == channel)
            .enumerate()
        {
            if index % 512 == 0 {
                token.checkpoint()?;
            }
            write_mark(&mut svg, scale_mark(mark.clone(), scale_x, scale_y), index)?;
        }
        writeln!(svg, "  </g>")?;
    }
    writeln!(svg, "</svg>")?;
    atomic_write_cancellable(path, svg.as_bytes(), token)
}

fn export_curve_svg(
    path: &Path,
    document: &Document,
    geometry: &crate::curve_render::CurveGeometry,
    token: &CancellationToken,
) -> Result<()> {
    token.checkpoint()?;
    let mut svg = String::new();
    writeln!(
        svg,
        r#"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="{}" height="{}" viewBox="0 0 {} {}" style="isolation:isolate">"#,
        geometry.width, geometry.height, geometry.width, geometry.height
    )?;
    writeln!(
        svg,
        "  <title>Toniator — {}</title>",
        xml_escape(&document.source.name)
    )?;
    writeln!(
        svg,
        "  <desc>Editable {} full-width curve halftone generated by Toniator</desc>",
        if document.artwork_pipeline.output_model == crate::artwork_pipeline::OutputModel::RgbScreen
        {
            "RGB screen"
        } else {
            "CMYK ink"
        }
    )?;
    writeln!(
        svg,
        "  <defs><clipPath id=\"toniator-artboard-clip\"><rect x=\"0\" y=\"0\" width=\"{}\" height=\"{}\"/></clipPath></defs>",
        geometry.width, geometry.height
    )?;
    write_export_background(&mut svg, document.appearance.export_background)?;
    let crosshatch_compatibility = matches!(
        document.artwork_pipeline.assignment,
        ChannelAssignment::LegacyCompatibility(
            LegacyCompatibilityAssignment::CrosshatchProgressiveKcmyV1
        )
    );
    for layer in &geometry.layers {
        token.checkpoint()?;
        let channel = layer.layer.channel;
        let (r, g, b) = layer.layer.color;
        let label = if crosshatch_compatibility {
            match channel {
                Channel::Black => "Layer 1 (K)",
                Channel::Cyan => "Layer 2 (C)",
                Channel::Magenta => "Layer 3 (M)",
                Channel::Yellow => "Layer 4 (Y)",
                Channel::Red => "Red",
                Channel::Green => "Green",
                Channel::Blue => "Blue",
            }
        } else {
            match channel {
                Channel::Cyan => "Cyan",
                Channel::Magenta => "Magenta",
                Channel::Yellow => "Yellow",
                Channel::Black => "Black",
                Channel::Red => "Red",
                Channel::Green => "Green",
                Channel::Blue => "Blue",
            }
        };
        writeln!(
            svg,
            "  <g id=\"toniator-{}\" inkscape:groupmode=\"layer\" inkscape:label=\"{}\" fill=\"#{:02x}{:02x}{:02x}\" opacity=\"{}\" style=\"mix-blend-mode:{}\" clip-path=\"url(#toniator-artboard-clip)\">",
            channel.id(),
            label,
            r,
            g,
            b,
            number(layer.layer.opacity),
            if !crosshatch_compatibility
                && document.artwork_pipeline.output_model
                    == crate::artwork_pipeline::OutputModel::RgbScreen
            {
                "screen"
            } else {
                "multiply"
            }
        )?;
        for (index, outline) in layer.outlines.iter().enumerate() {
            if index % 512 == 0 {
                token.checkpoint()?;
            }
            writeln!(
                svg,
                "    <path id=\"{}-curve-{}\" d=\"{}\" fill-rule=\"nonzero\"/>",
                channel.id(),
                index,
                outline.to_svg_path_data()
            )?;
        }
        writeln!(svg, "  </g>")?;
    }
    writeln!(svg, "</svg>")?;
    atomic_write_cancellable(path, svg.as_bytes(), token)
}

/// Serializes synthetic Stage 3 region/network fixtures as an editable SVG.
/// The artboard clip is explicit and subtractive geometry is emitted through
/// SVG masks, never as a background-coloured stroke.
pub fn canonical_pattern_svg_bytes(
    output: &CanonicalPatternOutput,
    title: &str,
) -> Result<Vec<u8>> {
    canonical_pattern_svg_bytes_cancellable(output, title, &CancellationToken::new())
}

pub fn canonical_pattern_svg_bytes_cancellable(
    output: &CanonicalPatternOutput,
    title: &str,
    token: &CancellationToken,
) -> Result<Vec<u8>> {
    token.checkpoint()?;
    output.validate().map_err(anyhow::Error::new)?;
    let artboard = output.artboard();
    let mut svg = String::new();
    writeln!(
        svg,
        r#"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="{}" height="{}" viewBox="0 0 {} {}" style="isolation:isolate">"#,
        artboard.width, artboard.height, artboard.width, artboard.height
    )?;
    writeln!(svg, "  <title>Toniator — {}</title>", xml_escape(title))?;
    writeln!(
        svg,
        "  <desc>Editable canonical pattern geometry generated by Toniator</desc>"
    )?;
    writeln!(
        svg,
        "  <defs><clipPath id=\"toniator-artboard-clip\"><rect x=\"0\" y=\"0\" width=\"{}\" height=\"{}\"/></clipPath>",
        artboard.width, artboard.height
    )?;
    match output {
        CanonicalPatternOutput::Regions(output) => write_region_svg(&mut svg, output, "", token)?,
        CanonicalPatternOutput::Network(output) => write_network_svg(&mut svg, output, "", token)?,
        CanonicalPatternOutput::Composite(output) => {
            if let Some(regions) = &output.regions {
                write_region_svg(&mut svg, regions, "regions-", token)?;
            }
            if let Some(network) = &output.network {
                write_network_svg(&mut svg, network, "network-", token)?;
            }
        }
        CanonicalPatternOutput::Marks(_) | CanonicalPatternOutput::Paths(_) => {
            // Marks and paths retain their established document SVG forms in
            // `export_svg_cancellable`; this helper is for new algebra forms.
        }
    }
    writeln!(svg, "  </defs>")?;
    match output {
        CanonicalPatternOutput::Regions(output) => {
            write_region_layers_svg(&mut svg, output, "", token)?
        }
        CanonicalPatternOutput::Network(output) => {
            write_network_layers_svg(&mut svg, output, "", token)?
        }
        CanonicalPatternOutput::Composite(output) => {
            if let Some(regions) = &output.regions {
                write_region_layers_svg(&mut svg, regions, "regions-", token)?;
            }
            if let Some(network) = &output.network {
                write_network_layers_svg(&mut svg, network, "network-", token)?;
            }
        }
        CanonicalPatternOutput::Marks(_) | CanonicalPatternOutput::Paths(_) => {}
    }
    writeln!(svg, "</svg>")?;
    token.checkpoint()?;
    Ok(svg.into_bytes())
}

fn ordered_layers(layers: &[CanonicalLayer]) -> Vec<&CanonicalLayer> {
    let mut layers: Vec<_> = layers.iter().collect();
    layers.sort_by_key(|layer| (layer.order, layer.id));
    layers
}

fn write_region_svg(
    svg: &mut String,
    output: &RegionPatternOutput,
    mask_prefix: &str,
    token: &CancellationToken,
) -> std::fmt::Result {
    for layer in ordered_layers(&output.layers) {
        token.checkpoint().map_err(|_| std::fmt::Error)?;
        let negatives: Vec<_> = output
            .regions
            .iter()
            .filter(|region| {
                region.layer_id == layer.id && region.polarity == GeometryPolarity::Subtractive
            })
            .collect();
        if negatives.is_empty() {
            continue;
        }
        writeln!(
            svg,
            "    <mask id=\"toniator-{}layer-{}-subtract\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"{}\" height=\"{}\"><rect x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"white\"/>",
            mask_prefix, layer.id.0, output.artboard.width, output.artboard.height
        )?;
        for region in negatives {
            token.checkpoint().map_err(|_| std::fmt::Error)?;
            writeln!(
                svg,
                "      <path d=\"{}\" fill=\"black\" fill-rule=\"{}\"{} />",
                region_path_data(region),
                svg_fill_rule(region.fill_rule),
                svg_transform(region.transform)
            )?;
        }
        writeln!(svg, "    </mask>")?;
    }
    Ok(())
}

fn write_region_layers_svg(
    svg: &mut String,
    output: &RegionPatternOutput,
    mask_prefix: &str,
    token: &CancellationToken,
) -> std::fmt::Result {
    for layer in ordered_layers(&output.layers) {
        token.checkpoint().map_err(|_| std::fmt::Error)?;
        let has_subtraction = output.regions.iter().any(|region| {
            region.layer_id == layer.id && region.polarity == GeometryPolarity::Subtractive
        });
        writeln!(
            svg,
            "  <g id=\"toniator-{}layer-{}\" inkscape:groupmode=\"layer\" inkscape:label=\"{}\" fill=\"#{:02x}{:02x}{:02x}\" opacity=\"{}\" style=\"mix-blend-mode:{}\" clip-path=\"url(#toniator-artboard-clip)\"{}>",
            mask_prefix,
            layer.id.0,
            xml_escape(&layer.label),
            layer.color.red,
            layer.color.green,
            layer.color.blue,
            number(layer.opacity),
            svg_blend_mode(layer.blend_mode),
            if has_subtraction {
                format!(
                    " mask=\"url(#toniator-{}layer-{}-subtract)\"",
                    mask_prefix, layer.id.0
                )
            } else {
                String::new()
            }
        )?;
        let mut regions: Vec<_> = output
            .regions
            .iter()
            .filter(|region| {
                region.layer_id == layer.id && region.polarity == GeometryPolarity::Positive
            })
            .collect();
        regions.sort_by_key(|region| (region.order, region.id));
        for region in regions {
            token.checkpoint().map_err(|_| std::fmt::Error)?;
            writeln!(
                svg,
                "    <path id=\"toniator-{}layer-{}-region-{}\" d=\"{}\" fill-rule=\"{}\"{} />",
                mask_prefix,
                layer.id.0,
                region.id.0,
                region_path_data(region),
                svg_fill_rule(region.fill_rule),
                svg_transform(region.transform)
            )?;
        }
        writeln!(svg, "  </g>")?;
    }
    Ok(())
}

fn write_network_svg(
    svg: &mut String,
    output: &NetworkPatternOutput,
    mask_prefix: &str,
    token: &CancellationToken,
) -> std::fmt::Result {
    for layer in ordered_layers(&output.layers) {
        token.checkpoint().map_err(|_| std::fmt::Error)?;
        let negatives: Vec<_> = output
            .edges
            .iter()
            .filter(|edge| {
                edge.layer_id == layer.id && edge.polarity == GeometryPolarity::Subtractive
            })
            .collect();
        if negatives.is_empty() {
            continue;
        }
        writeln!(
            svg,
            "    <mask id=\"toniator-{}layer-{}-subtract\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"{}\" height=\"{}\"><rect x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"white\"/>",
            mask_prefix, layer.id.0, output.artboard.width, output.artboard.height
        )?;
        for edge in negatives {
            token.checkpoint().map_err(|_| std::fmt::Error)?;
            writeln!(
                svg,
                "      <path d=\"{}\" fill=\"none\" stroke=\"black\" stroke-width=\"{}\"{} />",
                network_edge_path_data(output, edge.start, edge.end),
                number(edge.width),
                svg_transform(output.transform)
            )?;
        }
        writeln!(svg, "    </mask>")?;
    }
    Ok(())
}

fn write_network_layers_svg(
    svg: &mut String,
    output: &NetworkPatternOutput,
    mask_prefix: &str,
    token: &CancellationToken,
) -> std::fmt::Result {
    for layer in ordered_layers(&output.layers) {
        token.checkpoint().map_err(|_| std::fmt::Error)?;
        let has_subtraction = output.edges.iter().any(|edge| {
            edge.layer_id == layer.id && edge.polarity == GeometryPolarity::Subtractive
        });
        writeln!(
            svg,
            "  <g id=\"toniator-{}layer-{}\" inkscape:groupmode=\"layer\" inkscape:label=\"{}\" fill=\"none\" stroke=\"#{:02x}{:02x}{:02x}\" opacity=\"{}\" style=\"mix-blend-mode:{}\" clip-path=\"url(#toniator-artboard-clip)\"{}>",
            mask_prefix,
            layer.id.0,
            xml_escape(&layer.label),
            layer.color.red,
            layer.color.green,
            layer.color.blue,
            number(layer.opacity),
            svg_blend_mode(layer.blend_mode),
            if has_subtraction {
                format!(
                    " mask=\"url(#toniator-{}layer-{}-subtract)\"",
                    mask_prefix, layer.id.0
                )
            } else {
                String::new()
            }
        )?;
        let mut edges: Vec<_> = output
            .edges
            .iter()
            .filter(|edge| edge.layer_id == layer.id && edge.polarity == GeometryPolarity::Positive)
            .collect();
        edges.sort_by_key(|edge| (edge.order, edge.id));
        for edge in edges {
            token.checkpoint().map_err(|_| std::fmt::Error)?;
            writeln!(
                svg,
                "    <path id=\"toniator-{}layer-{}-edge-{}\" d=\"{}\" stroke-width=\"{}\"{} />",
                mask_prefix,
                layer.id.0,
                edge.id.0,
                network_edge_path_data(output, edge.start, edge.end),
                number(edge.width),
                svg_transform(output.transform)
            )?;
        }
        writeln!(svg, "  </g>")?;
    }
    Ok(())
}

fn region_path_data(region: &crate::pattern::FilledRegion) -> String {
    let mut path = String::new();
    for ring in &region.rings {
        if !path.is_empty() {
            path.push(' ');
        }
        let first = ring.vertices[0];
        path.push_str(&format!("M {} {}", number(first.x), number(first.y)));
        for point in &ring.vertices[1..] {
            path.push_str(&format!(" L {} {}", number(point.x), number(point.y)));
        }
        path.push_str(" Z");
    }
    path
}

fn network_edge_path_data(
    output: &NetworkPatternOutput,
    start: crate::pattern::NetworkNodeId,
    end: crate::pattern::NetworkNodeId,
) -> String {
    let start = output
        .nodes
        .iter()
        .find(|node| node.id == start)
        .expect("validated node")
        .point;
    let end = output
        .nodes
        .iter()
        .find(|node| node.id == end)
        .expect("validated node")
        .point;
    format!(
        "M {} {} L {} {}",
        number(start.x),
        number(start.y),
        number(end.x),
        number(end.y)
    )
}

fn svg_fill_rule(fill_rule: crate::pattern::FillRule) -> &'static str {
    match fill_rule {
        crate::pattern::FillRule::NonZero => "nonzero",
        crate::pattern::FillRule::EvenOdd => "evenodd",
    }
}

fn svg_blend_mode(mode: CanonicalBlendMode) -> &'static str {
    match mode {
        CanonicalBlendMode::Multiply => "multiply",
        CanonicalBlendMode::Screen => "screen",
    }
}

fn svg_transform(transform: crate::pattern::AffineTransform) -> String {
    if transform == crate::pattern::AffineTransform::IDENTITY {
        String::new()
    } else {
        format!(
            " transform=\"matrix({} {} {} {} {} {})\"",
            number(transform.xx),
            number(transform.yx),
            number(transform.xy),
            number(transform.yy),
            number(transform.dx),
            number(transform.dy)
        )
    }
}

fn write_export_background(svg: &mut String, background: ExportBackground) -> std::fmt::Result {
    let ExportBackground::Color { color } = background else {
        return Ok(());
    };
    write!(
        svg,
        "  <g id=\"toniator-background\" inkscape:groupmode=\"layer\" inkscape:label=\"Export Background\"><rect x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"#{:02x}{:02x}{:02x}\"",
        color.red, color.green, color.blue
    )?;
    if color.alpha != 255 {
        write!(
            svg,
            " fill-opacity=\"{}\"",
            number(color.alpha as f32 / 255.0)
        )?;
    }
    writeln!(svg, "/></g>")
}

fn scale_mark(mut mark: Mark, scale_x: f32, scale_y: f32) -> Mark {
    mark.x *= scale_x;
    mark.y *= scale_y;
    mark.extent *= (scale_x + scale_y) / 2.0;
    mark.thickness *= (scale_x + scale_y) / 2.0;
    mark
}

fn write_mark(svg: &mut String, mark: Mark, index: usize) -> std::fmt::Result {
    let prefix = mark.channel.id();
    if let MarkGeometry::WebShape(shape) = mark.geometry.clone() {
        return writeln!(
            svg,
            "    <path id=\"{}-mark-{}\" d=\"{}\"/>",
            prefix,
            index,
            web_shape_path_data(mark, shape)
        );
    }
    match mark.treatment {
        Treatment::Dots => writeln!(
            svg,
            "    <circle id=\"{}-mark-{}\" cx=\"{}\" cy=\"{}\" r=\"{}\"/>",
            prefix,
            index,
            number(mark.x),
            number(mark.y),
            number(mark.extent)
        ),
        Treatment::Squares => writeln!(
            svg,
            "    <rect id=\"{}-mark-{}\" x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" transform=\"rotate({} {} {})\"/>",
            prefix,
            index,
            number(mark.x - mark.extent / 2.0),
            number(mark.y - mark.extent / 2.0),
            number(mark.extent),
            number(mark.extent),
            number(mark.angle),
            number(mark.x),
            number(mark.y)
        ),
        Treatment::Lines => writeln!(
            svg,
            "    <rect id=\"{}-mark-{}\" x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" transform=\"rotate({} {} {})\"/>",
            prefix,
            index,
            number(mark.x - mark.extent / 2.0),
            number(mark.y - mark.thickness / 2.0),
            number(mark.extent),
            number(mark.thickness),
            number(mark.angle),
            number(mark.x),
            number(mark.y)
        ),
    }
}

fn web_shape_path_data(mark: Mark, shape: ResolvedWebShape) -> String {
    let transform = |x: f32, y: f32| {
        let radians = mark.angle.to_radians();
        let (sin, cos) = radians.sin_cos();
        let x = x * mark.extent;
        let y = y * mark.thickness;
        (mark.x + x * cos - y * sin, mark.y + x * sin + y * cos)
    };
    let point = |(x, y)| {
        let (x, y) = transform(x, y);
        format!("{} {}", number(x), number(y))
    };
    if matches!(shape, ResolvedWebShape::Circle) {
        let p = [
            (0.0, -0.5),
            (0.276, -0.5),
            (0.5, -0.276),
            (0.5, 0.0),
            (0.5, 0.276),
            (0.276, 0.5),
            (0.0, 0.5),
            (-0.276, 0.5),
            (-0.5, 0.276),
            (-0.5, 0.0),
            (-0.5, -0.276),
            (-0.276, -0.5),
            (0.0, -0.5),
        ];
        return format!(
            "M {} C {} {} {} C {} {} {} C {} {} {} C {} {} {} Z",
            point(p[0]),
            point(p[1]),
            point(p[2]),
            point(p[3]),
            point(p[4]),
            point(p[5]),
            point(p[6]),
            point(p[7]),
            point(p[8]),
            point(p[9]),
            point(p[10]),
            point(p[11]),
            point(p[12]),
        );
    }
    if let ResolvedWebShape::Polygon(points) = shape {
        let mut data = format!("M {}", point(points[0]));
        for &vertex in &points[1..] {
            data.push_str(" L ");
            data.push_str(&point(vertex));
        }
        data.push_str(" Z");
        return data;
    }
    let ResolvedWebShape::Cubic { start, segments } = shape else {
        unreachable!()
    };
    let mut data = format!("M {}", point(start));
    for segment in segments.iter() {
        data.push_str(" C ");
        data.push_str(&point((segment.0, segment.1)));
        data.push(' ');
        data.push_str(&point((segment.2, segment.3)));
        data.push(' ');
        data.push_str(&point((segment.4, segment.5)));
    }
    data.push_str(" Z");
    data
}

fn number(value: f32) -> String {
    let mut number = format!("{value:.3}");
    while number.contains('.') && number.ends_with('0') {
        number.pop();
    }
    if number.ends_with('.') {
        number.pop();
    }
    if number == "-0" { "0".into() } else { number }
}

fn xml_escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{
        DocumentAppearance, DocumentEditor, OutputMode, PreviewSurface, RgbaColor, SourceArtwork,
    };
    use crate::pattern::{
        AffineTransform, ArtboardSpace, CanonicalBlendMode, CanonicalColor, CanonicalLayer,
        CanonicalLayerId, CanonicalPatternOutput, CanonicalPoint, CompositePatternOutput, FillRule,
        FilledRegion, GeometryPolarity, NetworkEdgeId, NetworkNode, NetworkNodeId,
        NetworkPatternOutput, PolygonRing, RegionId, RegionPatternOutput, RingWinding,
        SharedBoundaryEdge,
    };
    use crate::preset::parse_treatment;
    use image::{DynamicImage, ImageFormat, Rgb, RgbImage, Rgba, RgbaImage};
    use std::io::Cursor;

    fn source_png() -> Vec<u8> {
        let image = RgbImage::from_fn(48, 32, |x, y| {
            Rgb([(x * 5) as u8, (y * 7) as u8, ((x + y) * 3) as u8])
        });
        let mut bytes = Cursor::new(Vec::new());
        DynamicImage::ImageRgb8(image)
            .write_to(&mut bytes, ImageFormat::Png)
            .unwrap();
        bytes.into_inner()
    }

    fn c1_fixture_source() -> SourceArtwork {
        // Match the current fixtures' 900 × 620 ratio so this parity test
        // isolates SVG authority and presentation semantics.
        let image = RgbaImage::from_fn(45, 31, |x, y| {
            Rgba([
                (20 + x * 4) as u8,
                (40 + y * 3) as u8,
                (180 - ((x + y) % 20) * 7) as u8,
                255,
            ])
        });
        let mut bytes = Cursor::new(Vec::new());
        DynamicImage::ImageRgba8(image)
            .write_to(&mut bytes, ImageFormat::Png)
            .unwrap();
        SourceArtwork {
            name: "c1-fixture-source.png".into(),
            media_type: "image/png".into(),
            bytes: bytes.into_inner().into(),
        }
    }

    fn contradictory_adapter_for(pattern: crate::pattern::PatternId) -> RenderVariant {
        match pattern {
            crate::pattern::PatternId::COMPATIBILITY_SHAPES_V1 => RenderVariant::WebCurveV1 {
                settings: Box::new(crate::model::WebCurveSettings {
                    output_width: 19,
                    output_height: 13,
                    long_edge_cells: 2.0,
                    max_mark: 91.0,
                    ..Default::default()
                }),
            },
            crate::pattern::PatternId::COMPATIBILITY_CURVES_V1 => RenderVariant::WebShapeV1 {
                settings: Box::new(crate::model::WebShapeSettings {
                    output_width: 17,
                    output_height: 11,
                    long_edge_cells: 2.0,
                    grid_scale: 77.0,
                    polygon_sides: 3,
                    ..Default::default()
                }),
            },
        }
    }

    fn exported_svg_bytes(document: &Document) -> Vec<u8> {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("fixture.svg");
        export_svg(&path, document).unwrap();
        std::fs::read(path).unwrap()
    }

    fn rasterize_svg(svg: &[u8], width: u32, height: u32) -> RgbaImage {
        let tree = usvg::Tree::from_data(svg, &usvg::Options::default()).unwrap();
        let mut pixmap = tiny_skia::Pixmap::new(width, height).unwrap();
        resvg::render(
            &tree,
            tiny_skia::Transform::identity(),
            &mut pixmap.as_mut(),
        );
        RgbaImage::from_raw(width, height, pixmap.data().to_vec()).unwrap()
    }

    fn canonical_region_fixture() -> CanonicalPatternOutput {
        let clockwise = |points: &[(f32, f32)]| PolygonRing {
            vertices: points
                .iter()
                .map(|&(x, y)| CanonicalPoint { x, y })
                .collect(),
            winding: RingWinding::Clockwise,
        };
        let counter_clockwise = |points: &[(f32, f32)]| PolygonRing {
            vertices: points
                .iter()
                .map(|&(x, y)| CanonicalPoint { x, y })
                .collect(),
            winding: RingWinding::CounterClockwise,
        };
        CanonicalPatternOutput::Regions(RegionPatternOutput {
            artboard: ArtboardSpace {
                width: 12,
                height: 12,
            },
            layers: vec![CanonicalLayer {
                id: CanonicalLayerId(1),
                channel: None,
                label: "Fixture Cell Layer".into(),
                order: 0,
                color: CanonicalColor {
                    red: 210,
                    green: 40,
                    blue: 50,
                },
                opacity: 0.5,
                blend_mode: CanonicalBlendMode::Multiply,
            }],
            regions: vec![
                FilledRegion {
                    id: RegionId(1),
                    layer_id: CanonicalLayerId(1),
                    order: 0,
                    rings: vec![
                        clockwise(&[(1.0, 1.0), (11.0, 1.0), (11.0, 11.0), (1.0, 11.0)]),
                        counter_clockwise(&[(4.0, 4.0), (4.0, 8.0), (8.0, 8.0), (8.0, 4.0)]),
                    ],
                    fill_rule: FillRule::EvenOdd,
                    polarity: GeometryPolarity::Positive,
                    transform: AffineTransform::IDENTITY,
                },
                FilledRegion {
                    id: RegionId(2),
                    layer_id: CanonicalLayerId(1),
                    order: 1,
                    rings: vec![clockwise(&[
                        (9.0, 1.0),
                        (11.0, 1.0),
                        (11.0, 3.0),
                        (9.0, 3.0),
                    ])],
                    fill_rule: FillRule::NonZero,
                    polarity: GeometryPolarity::Subtractive,
                    transform: AffineTransform::IDENTITY,
                },
            ],
        })
    }

    #[test]
    fn canonical_region_svg_has_editable_groups_masks_and_raster_parity() {
        let output = canonical_region_fixture();
        let svg = canonical_pattern_svg_bytes(&output, "fixture").unwrap();
        let text = String::from_utf8(svg.clone()).unwrap();
        assert!(text.contains("inkscape:groupmode=\"layer\""));
        assert!(text.contains("fill-rule=\"evenodd\""));
        assert!(text.contains("<mask id=\"toniator-layer-1-subtract\""));
        assert!(text.contains("clip-path=\"url(#toniator-artboard-clip)\""));
        usvg::Tree::from_data(&svg, &usvg::Options::default()).unwrap();

        let raster = crate::render::render_canonical_pattern_output_cancellable(
            &output,
            12,
            12,
            false,
            None,
            &CancellationToken::new(),
        )
        .unwrap();
        let svg_raster = crate::render::decode_source(
            &SourceArtwork {
                name: "fixture.svg".into(),
                media_type: "image/svg+xml".into(),
                bytes: std::sync::Arc::from(svg),
            },
            12,
        )
        .unwrap();
        let png =
            crate::png_export::canonical_pattern_png_bytes(&output, 12, 12, false, None).unwrap();
        let png_raster = image::load_from_memory(&png).unwrap().to_rgba8();
        for (x, y) in [(2, 2), (6, 6), (10, 2)] {
            assert!(
                (i16::from(raster.get_pixel(x, y)[3]) - i16::from(svg_raster.get_pixel(x, y)[3]))
                    .abs()
                    <= 1,
                "alpha mismatch at ({x}, {y})"
            );
            assert_eq!(raster.get_pixel(x, y), png_raster.get_pixel(x, y));
        }
    }

    #[test]
    fn canonical_composite_keeps_regions_and_shared_network_editable() {
        let CanonicalPatternOutput::Regions(regions) = canonical_region_fixture() else {
            unreachable!()
        };
        let output = CanonicalPatternOutput::Composite(CompositePatternOutput {
            artboard: regions.artboard,
            regions: Some(regions),
            network: Some(NetworkPatternOutput {
                artboard: ArtboardSpace {
                    width: 12,
                    height: 12,
                },
                layers: vec![CanonicalLayer {
                    id: CanonicalLayerId(1),
                    channel: None,
                    label: "Shared Cell Boundaries".into(),
                    order: 1,
                    color: CanonicalColor {
                        red: 20,
                        green: 30,
                        blue: 40,
                    },
                    opacity: 1.0,
                    blend_mode: CanonicalBlendMode::Multiply,
                }],
                nodes: vec![
                    NetworkNode {
                        id: NetworkNodeId(1),
                        point: CanonicalPoint { x: 1.0, y: 6.0 },
                    },
                    NetworkNode {
                        id: NetworkNodeId(2),
                        point: CanonicalPoint { x: 11.0, y: 6.0 },
                    },
                ],
                edges: vec![SharedBoundaryEdge {
                    id: NetworkEdgeId(1),
                    layer_id: CanonicalLayerId(1),
                    order: 0,
                    start: NetworkNodeId(1),
                    end: NetworkNodeId(2),
                    width: 0.5,
                    polarity: GeometryPolarity::Positive,
                }],
                transform: AffineTransform::IDENTITY,
            }),
        });
        output.validate().unwrap();
        let svg = canonical_pattern_svg_bytes(&output, "composite").unwrap();
        let text = String::from_utf8(svg.clone()).unwrap();
        assert!(text.contains("toniator-regions-layer-1"));
        assert!(text.contains("toniator-network-layer-1"));
        assert!(text.contains("id=\"toniator-regions-layer-1-region-1\""));
        assert!(text.contains("id=\"toniator-network-layer-1-edge-1\""));
        usvg::Tree::from_data(&svg, &usvg::Options::default()).unwrap();
        let raster = crate::render::render_canonical_pattern_output_cancellable(
            &output,
            12,
            12,
            false,
            None,
            &CancellationToken::new(),
        )
        .unwrap();
        assert!(raster.get_pixel(6, 6)[3] > 0);
    }

    #[test]
    fn svg_has_editable_named_layers_and_no_source_image() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("result.svg");
        let document = Document::new(SourceArtwork {
            name: "gradient.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        for channel in ["cyan", "magenta", "yellow", "black"] {
            assert!(svg.contains(&format!("id=\"toniator-{channel}\"")));
        }
        assert!(svg.contains("<path"));
        assert!(svg.contains("mix-blend-mode:multiply"));
        assert!(!svg.contains("<image"));
        let options = usvg::Options::default();
        usvg::Tree::from_data(svg.as_bytes(), &options).unwrap();
    }

    #[test]
    fn export_preserves_artboards_larger_than_preview_cap() {
        let image = RgbImage::from_pixel(3001, 2, Rgb([120, 40, 200]));
        let mut bytes = Cursor::new(Vec::new());
        DynamicImage::ImageRgb8(image)
            .write_to(&mut bytes, ImageFormat::Png)
            .unwrap();
        let mut document = Document::new(SourceArtwork {
            name: "wide.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(bytes.into_inner()),
        });
        document.render = RenderVariant::NativeBasicV1;
        document.pattern_state.select_native_basic();
        document
            .pattern_state
            .set_selected_parameters_for_test(&document.render);
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("wide.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        assert!(svg.contains("width=\"3001\" height=\"2\" viewBox=\"0 0 3001 2\""));
    }

    #[test]
    fn web_export_uses_the_preview_mark_set_and_resolved_layers() {
        use crate::model::{
            ClosedShapePath, Ink, RenderVariant, ShapePoint, ValueMode, WebShape, WebShapeSettings,
        };
        use crate::render::generate_document_marks;

        let mut document = Document::new(SourceArtwork {
            name: "black.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        let mut settings = WebShapeSettings {
            output_width: 120,
            output_height: 80,
            long_edge_cells: 6.0,
            grid_scale: 76.0,
            min_mark: 4.0,
            max_mark: 90.0,
            value_mode: ValueMode::SingleChannel,
            single_channel: Ink::Black,
            shared_shape: WebShape::UserDefined,
            ..Default::default()
        };
        let mut custom = ClosedShapePath::from_polygon(&settings.custom_nodes);
        custom.anchors[0].outgoing = ShapePoint { x: 0.1, y: -0.7 };
        custom.anchors[1].incoming = ShapePoint { x: 0.2, y: -0.1 };
        settings.custom_shape_path = Some(custom);
        for ink in Ink::ALL {
            settings.channels.get_mut(ink).enabled = ink == Ink::Black;
        }
        settings.channels.k.color = "#123456".into();
        settings.channels.k.opacity = 0.37;
        document.render = RenderVariant::WebShapeV1 {
            settings: Box::new(settings),
        };
        document
            .pattern_state
            .set_selected_parameters_for_test(&document.render);
        document.appearance.export_background = ExportBackground::Color {
            color: crate::model::RgbaColor::WHITE,
        };

        let resolved = generate_document_marks(&document).unwrap();
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("web.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        assert!(svg.contains("width=\"120\" height=\"80\" viewBox=\"0 0 120 80\""));
        assert!(svg.contains("id=\"toniator-black\""));
        assert!(svg.contains("fill=\"#123456\" opacity=\"0.37\""));
        assert!(!svg.contains("id=\"toniator-cyan\""));
        assert!(!svg.contains("id=\"toniator-magenta\""));
        assert!(!svg.contains("id=\"toniator-yellow\""));
        assert!(!svg.contains("<image"));
        assert_eq!(svg.matches("<path id=\"").count(), resolved.marks.len());
        assert!(
            svg.contains(" C "),
            "custom cubic geometry must remain editable paths"
        );
        let tree = usvg::Tree::from_data(svg.as_bytes(), &usvg::Options::default()).unwrap();
        let mut rasterized = tiny_skia::Pixmap::new(120, 80).unwrap();
        resvg::render(
            &tree,
            tiny_skia::Transform::identity(),
            &mut rasterized.as_mut(),
        );
        let canonical =
            crate::render::render_document_output(&document, 120, 80, true, None).unwrap();
        let maximum_channel_drift = rasterized
            .data()
            .iter()
            .zip(canonical.as_raw())
            .map(|(svg, preview)| svg.abs_diff(*preview))
            .max()
            .unwrap_or(0);
        assert!(
            maximum_channel_drift <= 8,
            "SVG/preview raster drift {maximum_channel_drift}"
        );
    }

    #[test]
    fn c3b_c1_fixtures_svg_shares_authoritative_geometry_and_presentation() {
        for (name, bytes, selected) in [
            (
                "polygon-six",
                include_bytes!("../assets/presets/Polygon Six.tntr").as_slice(),
                crate::pattern::PatternId::COMPATIBILITY_SHAPES_V1,
            ),
            (
                "motif-ladder",
                include_bytes!("../assets/presets/Motif Ladder.tntr").as_slice(),
                crate::pattern::PatternId::COMPATIBILITY_CURVES_V1,
            ),
        ] {
            let mut fixture_editor = DocumentEditor::new(Document::new(c1_fixture_source()));
            let candidate = parse_treatment(bytes, (900, 620))
                .unwrap_or_else(|error| panic!("{name} did not parse: {error:#}"))
                .candidate_for(fixture_editor.document())
                .unwrap_or_else(|error| panic!("{name} did not apply: {error:#}"));
            assert!(fixture_editor.replace_with_preset_candidate(candidate));
            assert_eq!(
                fixture_editor
                    .document()
                    .pattern_state
                    .selected_pattern_id(),
                Some(selected)
            );
            assert!(fixture_editor.set_appearance(DocumentAppearance {
                preview_surface: PreviewSurface::Color {
                    color: RgbaColor::opaque(237, 241, 248),
                },
                export_background: ExportBackground::None,
            }));
            let canonical = fixture_editor.document().clone();

            // A deliberately opposite-kind facade must not influence either
            // the editable SVG geometry or its rasterized pattern output.
            let mut contradictory = canonical.clone();
            contradictory.render = contradictory_adapter_for(selected);
            let before_export = contradictory.clone();
            let raw = crate::render::render_document_output(&contradictory, 900, 620, false, None)
                .unwrap();
            let preview = crate::render::render_document_preview(&contradictory, 900, 1)
                .unwrap()
                .image;
            assert_eq!(
                preview,
                crate::render::composite_preview(raw.clone(), contradictory.appearance),
                "{name} preview remains the authoritative raw pattern plus Preview Surface"
            );
            let svg = exported_svg_bytes(&contradictory);
            assert_eq!(
                contradictory, before_export,
                "{name} SVG projection is read-only"
            );
            assert_eq!(
                svg,
                exported_svg_bytes(&contradictory),
                "{name} SVG export is deterministic"
            );
            assert_eq!(
                svg,
                exported_svg_bytes(&canonical),
                "{name} active adapter cannot alter SVG geometry"
            );
            let text = String::from_utf8(svg.clone()).unwrap();
            assert!(text.contains("Editable CMYK ink"));
            assert!(!text.contains("toniator-background"));
            assert!(!text.contains("checkerboard"));
            assert!(!text.contains("<image"));
            for channel in ["cyan", "magenta", "yellow", "black"] {
                assert!(text.contains(&format!("id=\"toniator-{channel}\"")));
                assert!(text.contains("inkscape:groupmode=\"layer\""));
            }
            let expected_editable_paths =
                match crate::render::generate_document_pattern_output(&contradictory).unwrap() {
                    CanonicalPatternOutput::Marks(output) => output.geometry.marks.len(),
                    CanonicalPatternOutput::Paths(output) => output
                        .geometry
                        .layers
                        .iter()
                        .map(|layer| layer.outlines.len())
                        .sum(),
                    _ => unreachable!("C1 fixtures are Shapes or Curves"),
                };
            assert_eq!(text.matches("<path id=").count(), expected_editable_paths);
            match selected {
                crate::pattern::PatternId::COMPATIBILITY_SHAPES_V1 => {
                    assert!(text.contains("-mark-"));
                    assert!(text.contains(" L "));
                    assert!(text.contains(" Z\"/>"));
                }
                crate::pattern::PatternId::COMPATIBILITY_CURVES_V1 => {
                    assert!(text.contains("-curve-"));
                    assert!(text.contains("clip-path=\"url(#toniator-artboard-clip)\""));
                    assert!(text.contains(" C "));
                }
            }
            usvg::Tree::from_data(&svg, &usvg::Options::default()).unwrap();
            let svg_raster = rasterize_svg(&svg, 900, 620);
            assert!(raw.pixels().any(|pixel| pixel[3] < 255));
            assert!(svg_raster.pixels().any(|pixel| pixel[3] < 255));
            let mean_channel_drift = svg_raster
                .as_raw()
                .iter()
                .zip(raw.as_raw())
                .map(|(svg, output)| u64::from(svg.abs_diff(*output)))
                .sum::<u64>() as f64
                / svg_raster.as_raw().len() as f64;
            assert!(
                mean_channel_drift <= 1.0,
                "{name} SVG/raw mean raster drift {mean_channel_drift}"
            );

            // Preview Surface never appears in an SVG; the saved Export
            // Background is the only presentation state allowed to do so.
            contradictory.appearance.preview_surface = PreviewSurface::Checkerboard;
            assert_eq!(
                exported_svg_bytes(&contradictory),
                svg,
                "{name} Preview Surface cannot change SVG bytes"
            );
            let preview_before_export_background =
                crate::render::render_document_preview(&contradictory, 900, 2)
                    .unwrap()
                    .image;
            let export_background = ExportBackground::Color {
                color: RgbaColor::opaque(12, 34, 56),
            };
            contradictory.appearance.export_background = export_background;
            let background_svg = exported_svg_bytes(&contradictory);
            assert_eq!(
                background_svg,
                exported_svg_bytes(&contradictory),
                "{name} Export Background SVG is deterministic"
            );
            let background_text = String::from_utf8(background_svg.clone()).unwrap();
            assert!(background_text.contains("id=\"toniator-background\""));
            assert!(background_text.contains("fill=\"#0c2238\""));
            assert!(
                background_text.find("toniator-background").unwrap()
                    < background_text.find("toniator-cyan").unwrap()
            );
            assert_eq!(
                crate::render::render_document_preview(&contradictory, 900, 3)
                    .unwrap()
                    .image,
                preview_before_export_background,
                "{name} Export Background cannot change preview pixels"
            );
            // The inactive CMYK facade is separately contradictory while RGB
            // is active. Cache restoration must rebuild its SVG from cached
            // typed authority before any geometry is emitted.
            let mut cache_editor = DocumentEditor::new(contradictory);
            assert!(cache_editor.set_output_mode(OutputMode::RgbScreen));
            let mut inactive_contradiction = cache_editor.document().clone();
            inactive_contradiction
                .inactive_cmyk
                .as_mut()
                .expect("CMYK treatment is cached while RGB is active")
                .render = contradictory_adapter_for(selected);
            let mut cache_editor = DocumentEditor::new(inactive_contradiction);
            assert!(cache_editor.set_output_mode(OutputMode::CmykInks));
            let restored = cache_editor.document().clone();
            assert_eq!(restored.pattern_state, canonical.pattern_state);
            assert_eq!(
                exported_svg_bytes(&restored),
                background_svg,
                "{name} inactive adapter cannot alter restored SVG geometry or background"
            );
        }
    }

    #[test]
    fn svg_uses_authoritative_output_model_when_legacy_facade_is_stale() {
        use crate::artwork_pipeline::{
            ArtworkPipelineSettings, AutomaticSeparationStrategy, ChannelAssignment, OutputModel,
            SourceAlphaPolicy,
        };
        use crate::model::{Ink, RenderVariant, ValueMode, WebShapeSettings};

        let mut document = Document::new(SourceArtwork {
            name: "rgb-authority.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        let mut settings = WebShapeSettings {
            output_width: 120,
            output_height: 80,
            long_edge_cells: 8.0,
            value_mode: ValueMode::Cmyk,
            ..Default::default()
        };
        for ink in Ink::ALL {
            settings.channels.get_mut(ink).enabled = false;
        }
        for ink in Ink::RGB {
            settings.channels.get_mut(ink).enabled = true;
        }
        document.render = RenderVariant::WebShapeV1 {
            settings: Box::new(settings),
        };
        document
            .pattern_state
            .set_selected_parameters_for_test(&document.render);
        document.artwork_pipeline = ArtworkPipelineSettings {
            source: crate::artwork_pipeline::ArtworkSource::FullColor,
            alpha_policy: SourceAlphaPolicy::LegacyCurrentV1,
            output_model: OutputModel::RgbScreen,
            assignment: ChannelAssignment::automatic(
                AutomaticSeparationStrategy::RgbDirectEncodedComponentsV1,
            ),
            active_channel: Some(crate::artwork_pipeline::OutputChannelId::RgbRed),
        };

        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("rgb-authority.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        assert!(svg.contains("mix-blend-mode:screen"));
        assert!(svg.contains("Editable RGB screen halftone"));
        assert!(svg.contains("toniator-red"));
        assert!(!svg.contains("toniator-cyan"));
    }

    #[test]
    fn curve_export_uses_canonical_preview_outlines_and_editable_layers() {
        use crate::curve_render::generate_curve_geometry;
        use crate::model::{Ink, RenderVariant, ValueMode, WebCurveSettings};
        use crate::render::decode_source;

        let mut document = Document::new(SourceArtwork {
            name: "black.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        let mut settings = WebCurveSettings {
            output_width: 120,
            output_height: 80,
            long_edge_cells: 8.0,
            value_mode: ValueMode::SingleChannel,
            single_channel: Ink::Black,
            ..Default::default()
        };
        for ink in Ink::ALL {
            settings.channels.get_mut(ink).enabled = ink == Ink::Black;
        }
        settings.channels.k.color = "#123456".into();
        settings.channels.k.opacity = 0.37;
        document.render = RenderVariant::WebCurveV1 {
            settings: Box::new(settings.clone()),
        };
        document
            .pattern_state
            .select_pattern(crate::pattern::PatternId::COMPATIBILITY_CURVES_V1)
            .unwrap();
        document
            .pattern_state
            .set_selected_parameters_for_test(&document.render);
        let source = decode_source(&document.source, 2400).unwrap();
        let geometry = generate_curve_geometry(&source, &settings).unwrap();
        let expected = geometry
            .layers
            .iter()
            .map(|layer| layer.outlines.len())
            .sum::<usize>();
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("curve.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        assert!(svg.contains("width=\"120\" height=\"80\""));
        assert!(svg.contains("clip-path=\"url(#toniator-artboard-clip)\""));
        assert!(svg.contains("id=\"toniator-black\""));
        assert!(svg.contains("fill=\"#123456\" opacity=\"0.37\""));
        assert_eq!(svg.matches("-curve-").count(), expected);
        assert!(!svg.contains("<image"));
        usvg::Tree::from_data(svg.as_bytes(), &usvg::Options::default()).unwrap();
    }

    #[test]
    fn crosshatch_svg_labels_follow_the_authoritative_pipeline_when_facade_is_stale() {
        use crate::model::{RenderVariant, WebCurveSettings};

        let mut document = Document::new(SourceArtwork {
            name: "crosshatch.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        let mut settings = WebCurveSettings {
            output_width: 160,
            output_height: 120,
            crosshatch_color: "#234567".into(),
            ..Default::default()
        };
        settings.configure_crosshatch();
        document.render = RenderVariant::WebCurveV1 {
            settings: Box::new(settings),
        };
        document
            .pattern_state
            .select_pattern(crate::pattern::PatternId::COMPATIBILITY_CURVES_V1)
            .unwrap();
        document
            .pattern_state
            .set_selected_parameters_for_test(&document.render);
        document
            .apply_legacy_mapping_action(crate::model::ValueMode::CrosshatchLuminance)
            .unwrap();
        let RenderVariant::WebCurveV1 { settings } = &mut document.render else {
            panic!("Crosshatch uses Curves");
        };
        settings.value_mode = crate::model::ValueMode::Cmyk;
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("crosshatch.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        for label in ["Layer 1 (K)", "Layer 2 (C)", "Layer 3 (M)", "Layer 4 (Y)"] {
            assert!(svg.contains(&format!("inkscape:label=\"{label}\"")));
        }
        assert_eq!(svg.matches("fill=\"#234567\"").count(), 4);
        assert!(svg.contains("-curve-"));
        assert!(!svg.contains("-mark-"));
        usvg::Tree::from_data(svg.as_bytes(), &usvg::Options::default()).unwrap();
    }

    #[test]
    fn rgb_output_crosshatch_svg_uses_multiply_and_authoritative_labels() {
        use crate::model::{DocumentEditor, OutputMode, ValueMode};

        let document = Document::new(SourceArtwork {
            name: "rgb-crosshatch.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        let mut editor = DocumentEditor::new(document);
        assert!(editor.set_output_mode(OutputMode::RgbScreen));
        assert!(editor.apply_legacy_mapping_action(ValueMode::CrosshatchLuminance));
        let mut document = editor.document().clone();
        let RenderVariant::WebCurveV1 { settings } = &mut document.render else {
            panic!("Crosshatch uses Curves");
        };
        settings.value_mode = ValueMode::Cmyk;

        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("rgb-crosshatch.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        assert_eq!(svg.matches("mix-blend-mode:multiply").count(), 4);
        assert!(!svg.contains("mix-blend-mode:screen"));
        for label in ["Layer 1 (K)", "Layer 2 (C)", "Layer 3 (M)", "Layer 4 (Y)"] {
            assert!(svg.contains(&format!("inkscape:label=\"{label}\"")));
        }
    }

    #[test]
    fn rgb_curve_svg_uses_only_rgb_layers_when_legacy_facade_is_stale() {
        use crate::artwork_pipeline::{
            ArtworkPipelineSettings, AutomaticSeparationStrategy, ChannelAssignment, OutputModel,
            SourceAlphaPolicy,
        };
        use crate::model::{Ink, RenderVariant, ValueMode, WebCurveSettings};

        let mut document = Document::new(SourceArtwork {
            name: "rgb-curves.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        let mut settings = WebCurveSettings {
            output_width: 120,
            output_height: 80,
            long_edge_cells: 8.0,
            value_mode: ValueMode::Cmyk,
            ..Default::default()
        };
        for ink in Ink::RGB {
            settings.channels.get_mut(ink).enabled = true;
        }
        document.render = RenderVariant::WebCurveV1 {
            settings: Box::new(settings),
        };
        document
            .pattern_state
            .select_pattern(crate::pattern::PatternId::COMPATIBILITY_CURVES_V1)
            .unwrap();
        document
            .pattern_state
            .set_selected_parameters_for_test(&document.render);
        document.artwork_pipeline = ArtworkPipelineSettings {
            source: crate::artwork_pipeline::ArtworkSource::FullColor,
            alpha_policy: SourceAlphaPolicy::LegacyCurrentV1,
            output_model: OutputModel::RgbScreen,
            assignment: ChannelAssignment::automatic(
                AutomaticSeparationStrategy::RgbDirectEncodedComponentsV1,
            ),
            active_channel: Some(crate::artwork_pipeline::OutputChannelId::RgbRed),
        };

        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("rgb-curves.svg");
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(path).unwrap();
        for (id, label) in [("red", "Red"), ("green", "Green"), ("blue", "Blue")] {
            assert!(svg.contains(&format!("id=\"toniator-{id}\"")));
            assert!(svg.contains(&format!("inkscape:label=\"{label}\"")));
        }
        assert!(!svg.contains("toniator-black"));
        assert!(!svg.contains("inkscape:label=\"Black\""));
        assert!(svg.contains("mix-blend-mode:screen"));
    }

    #[test]
    fn export_background_is_optional_named_bottom_layer_with_alpha() {
        let mut document = Document::new(SourceArtwork {
            name: "background.png".into(),
            media_type: "image/png".into(),
            bytes: std::sync::Arc::from(source_png()),
        });
        document.appearance.preview_surface = crate::model::PreviewSurface::Color {
            color: crate::model::RgbaColor::opaque(14, 26, 41),
        };
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("background.svg");
        export_svg(&path, &document).unwrap();
        let transparent = std::fs::read_to_string(&path).unwrap();
        assert!(!transparent.contains("toniator-background"));
        assert!(!transparent.contains("checkerboard"));

        document.appearance.preview_surface = crate::model::PreviewSurface::Checkerboard;
        export_svg(&path, &document).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), transparent);

        document.appearance.export_background = ExportBackground::Color {
            color: crate::model::RgbaColor {
                red: 1,
                green: 2,
                blue: 3,
                alpha: 128,
            },
        };
        export_svg(&path, &document).unwrap();
        let svg = std::fs::read_to_string(&path).unwrap();
        assert_eq!(svg.matches("toniator-background").count(), 1);
        assert!(svg.contains("fill=\"#010203\" fill-opacity=\"0.502\""));
        assert!(svg.find("toniator-background").unwrap() < svg.find("toniator-black").unwrap());
    }
}
